apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myappms
  replicas: 3
  template:
    metadata:
      labels:
        app: myappms
    spec:
      containers:
      - name: nodejspod
        image: jesus8/nodejsapp3:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: myapp-svc
spec:     
  selector:
    app: myappms
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
